### ISSUE TITLE
ジャパンネット銀行 renamed ＰａｙＰａｙ銀行

### ISSUE THREAD

**Issue by grosgg** [zengin-code/source-data#11]
Today, Japan Net Bank (code 0033) has been renamed PayPay Bank https://www.paypay-bank.co.jp/namechange/index.html

I know the source data comes from http://ykaku.com/ginkokensaku/index.php but it seems they have not updated it yet.

Would it be okay for me to open a PR with up-to-date information?

**Comment by rosylilly** [comment]
@grosgg We are aware of the changes that have been made, but since this is a transition period, we do not think there is a need to rush the data changes.
https://help.japannetbank.co.jp/hc/ja/articles/900002790666

I am glad that you have considered PR for the change. However, we try to refrain from manually changing the data as much as possible since it involves changing hash values.

The data will be updated by mid-April at the latest, so we hope you can wait a little while.

**Comment by grosgg** [comment]
Thanks for your reply and date estimation @rosylilly. We will then wait for the update 🙇‍♂️
